# Generated by Django 5.2.6 on 2025-09-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
